config/routes.rb
Pkmbattle::Application.routes.draw do
  resources :computadors

  resources :testes

end

app/models/computador.rb
class Computador < ActiveRecord::Base
end

app/models/teste.rb
class Teste < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/computadors_controller.rb
class ComputadorsController < ApplicationController
  before_action :set_computador, only: [:show, :edit, :update, :destroy]

  # GET /computadors
  # GET /computadors.json
  def index
    @computadors = Computador.all
  end

  # GET /computadors/1
  # GET /computadors/1.json
  def show
  end

  # GET /computadors/new
  def new
    @computador = Computador.new
  end

  # GET /computadors/1/edit
  def edit
  end

  # POST /computadors
  # POST /computadors.json
  def create
    @computador = Computador.new(computador_params)

    respond_to do |format|
      if @computador.save
        format.html { redirect_to @computador, notice: 'Computador was successfully created.' }
        format.json { render action: 'show', status: :created, location: @computador }
      else
        format.html { render action: 'new' }
        format.json { render json: @computador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computadors/1
  # PATCH/PUT /computadors/1.json
  def update
    respond_to do |format|
      if @computador.update(computador_params)
        format.html { redirect_to @computador, notice: 'Computador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @computador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computadors/1
  # DELETE /computadors/1.json
  def destroy
    @computador.destroy
    respond_to do |format|
      format.html { redirect_to computadors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computador
      @computador = Computador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computador_params
      params.require(:computador).permit(:serial, :marca, :modelo, :cor, :placa)
    end
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: [:show, :edit, :update, :destroy]

  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render action: 'show', status: :created, location: @testis }
      else
        format.html { render action: 'new' }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1
  # PATCH/PUT /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis.destroy
    respond_to do |format|
      format.html { redirect_to testes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testis_params
      params.require(:testis).permit(:nome, :pagina, :erro, :defeito)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computadors_helper.rb
module ComputadorsHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/computadors/_form.html.erb
<%= form_for(@computador) do |f| %>
  <% if @computador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computador.errors.count, "error") %> prohibited this computador from being saved:</h2>

      <ul>
      <% @computador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :serial %><br>
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :cor %><br>
    <%= f.text_field :cor %>
  </div>
  <div class="field">
    <%= f.label :placa %><br>
    <%= f.text_field :placa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computadors/edit.html.erb
<h1>Editing computador</h1>

<%= render 'form' %>

<%= link_to 'Show', @computador %> |
<%= link_to 'Back', computadors_path %>

app/views/computadors/index.html.erb
<h1>Listing computadors</h1>

<table>
  <thead>
    <tr>
      <th>Serial</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Cor</th>
      <th>Placa</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @computadors.each do |computador| %>
      <tr>
        <td><%= computador.serial %></td>
        <td><%= computador.marca %></td>
        <td><%= computador.modelo %></td>
        <td><%= computador.cor %></td>
        <td><%= computador.placa %></td>
        <td><%= link_to 'Show', computador %></td>
        <td><%= link_to 'Edit', edit_computador_path(computador) %></td>
        <td><%= link_to 'Destroy', computador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computador', new_computador_path %>

app/views/computadors/new.html.erb
<h1>New computador</h1>

<%= render 'form' %>

<%= link_to 'Back', computadors_path %>

app/views/computadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serial:</strong>
  <%= @computador.serial %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @computador.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @computador.modelo %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @computador.cor %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @computador.placa %>
</p>

<%= link_to 'Edit', edit_computador_path(@computador) %> |
<%= link_to 'Back', computadors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pkmbattle</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testes/_form.html.erb
<%= form_for(@testis) do |f| %>
  <% if @testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% @testis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :pagina %><br>
    <%= f.text_field :pagina %>
  </div>
  <div class="field">
    <%= f.label :erro %><br>
    <%= f.text_field :erro %>
  </div>
  <div class="field">
    <%= f.label :defeito %><br>
    <%= f.text_field :defeito %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing testis</h1>

<%= render 'form' %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/index.html.erb
<h1>Listing testes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Pagina</th>
      <th>Erro</th>
      <th>Defeito</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @testes.each do |testis| %>
      <tr>
        <td><%= testis.nome %></td>
        <td><%= testis.pagina %></td>
        <td><%= testis.erro %></td>
        <td><%= testis.defeito %></td>
        <td><%= link_to 'Show', testis %></td>
        <td><%= link_to 'Edit', edit_testis_path(testis) %></td>
        <td><%= link_to 'Destroy', testis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teste', new_testis_path %>

app/views/testes/new.html.erb
<h1>New testis</h1>

<%= render 'form' %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @testis.nome %>
</p>

<p>
  <strong>Pagina:</strong>
  <%= @testis.pagina %>
</p>

<p>
  <strong>Erro:</strong>
  <%= @testis.erro %>
</p>

<p>
  <strong>Defeito:</strong>
  <%= @testis.defeito %>
</p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>